import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

// POST /api/admin/clear-old-data
// Dev-only. Deletes all predictions and all matches not scheduled for today,
// so stale hardcoded seed data doesn't block real results from showing.

export async function POST(req: NextRequest) {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Not available in production' }, { status: 403 })
  }

  const today = new Date().toISOString().split('T')[0]

  // 1. Delete all predictions (they'll be re-generated by the pipeline)
  const { error: predErr } = await supabase
    .from('predictions')
    .delete()
    .neq('id', 0)   // matches all rows

  if (predErr) {
    return NextResponse.json({ error: `predictions: ${predErr.message}` }, { status: 500 })
  }

  // 2. Delete matches that are NOT from today
  //    (keeps any real matches already upserted for today)
  const { error: matchErr } = await supabase
    .from('matches')
    .delete()
    .not('match_date', 'gte', `${today}T00:00:00`)

  if (matchErr) {
    return NextResponse.json({ error: `matches: ${matchErr.message}` }, { status: 500 })
  }

  return NextResponse.json({ success: true })
}